version: '3'

services:
  nginx:
    build: ./docker/nginx
    # container_name: "asas-back-nginx"
    container_name: "test-back-nginx"
    ports:
      # - "60080:80"
      - "60081:80"
      # - "60443:443"
      - "60444:443"
    depends_on:
      - php
    volumes:
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    container_name: "test-back-php"
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www:cached
  mysql:
    build: ./docker/mysql
    container_name: "test-back-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: test-back_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: passw0rd
      TZ: 'Asia/Tokyo'
    ports: 
      # - "63306:3306"
      - "63307:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      - ./db/dev:/var/lib/mysql
  node:
    image: node:12.13-alpine
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www